setup/README.md
Marked setup guide as tested for SysEleven MetaKube
=> docs: SysEleven MetaKube compatibility

setup/README.md, setup/acr/README.md
Removes bash-specifics and removes jq dependency for ACR
Fix #36
=> docs: Shell compatibility

.github/workflows/codeql-analysis.yml
Adds CodeQL pipeline checks for pushes and PRs to master and a regular cronjob checking the master branch
Fix #22
=> ci: CodeQL

connaisseur/tests/data/ad_request_deployments.json, connaisseur/tests/data/ad_request_pods.json, connaisseur/tests/data/ad_request_replicasets.json, connaisseur/tests/data/deployments.json, connaisseur/tests/data/pods.json, connaisseur/tests/data/replicasets.json, connaisseur/tests/test_exceptions.py, connaisseur/tests/test_mutate.py, connaisseur/tests/test_notary_api.py, connaisseur/tests/test_policy.py
Remove personal Docker Hub references, rename user who signed nothing, remove some German
=> refactor: Refactor tests

README.md, SECURITY.md, connaisseur/key_store.py, connaisseur/mutate.py, connaisseur/notary_api.py, connaisseur/policy.py, connaisseur/tests/test_keystore.py, connaisseur/tests/test_mutate.py, connaisseur/tests/test_notary_api.py, connaisseur/tests/test_trust_data.py, connaisseur/tests/test_validate.py, connaisseur/trust_data.py, connaisseur/validate.py, helm/Chart.yaml, helm/templates/namespace.yaml, helm/templates/webhook/_webhook.tpl, helm/templates/webhook/webhook.yaml, helm/values.yaml, requirements_dev.txt, setup/README.md
- adjust public keys in READMEs to DockerHub Repo [(#102)](https://github.com/sse-secure-systems/connaisseur/pull/102)
- adjust public keys in READMEs to DockerHub Repo [(#102)](https://github.com/sse-secure-systems/connaisseur/pull/102)
- Never use non-validated data for validation [(#89)](https://github.com/sse-secure-systems/connaisseur/pull/89)
- Enable Per-Namespace verification [(#100)](https://github.com/sse-secure-systems/connaisseur/pull/100)
- Reduce complexity of 'process_chain_of_trust' [(#89)](https://github.com/sse-secure-systems/connaisseur/pull/89)
- updated pylint [(#97)](https://github.com/sse-secure-systems/connaisseur/pull/97)
- updated pylint [(#97)](https://github.com/sse-secure-systems/connaisseur/pull/97)
=> Release 1.4.6

connaisseur/alert.py, connaisseur/tests/test_alert.py
Upgrading to 1.5.0 without pulling the newest version of the helm templates will result in a Configuration Error as there are configuration files missing that are needed for the alerting which came with 1.5.0. This fix ensures that one can update to the new image without failures even without repulling the connaisseur repo. The added feature will, however, not be functional without the new helm templates.
=> fix: ensure backwards compatibility when upgrading to 1.5.0

connaisseur/sigstore_validator.py, connaisseur/tests/test_sigstore_validator.py
If the `cosign` binary indicates successful successful signature verification by exiting with status code `0` but Connaisseur is not able to retrieve at least one valid image digest from the output from the `cosign` binary, the error message should show that this is a parsing issue. Right now, we would have thrown an error indicating that signature verification has failed which is misleading because the actual verification has already happened on the `cosign` side at this point.
=> fix: make error handling more specific

.github/actions/integration-test/action.yaml, .github/actions/safety/action.yaml, .github/actions/trivy/action.yaml, .github/workflows/cicd.yaml, .github/workflows/nightly-scans.yaml, .github/workflows/release.yaml
As we added more flavours of integration testing, we introduced some code duplication. This aims to remove redundance by using a private github action.
Fixes #112
=> refactor: refactor workflows to reduce code duplication

connaisseur/alert.py, connaisseur/exceptions.py, connaisseur/flask_server.py, connaisseur/tests/conftest.py, connaisseur/tests/data/alerting/alertconfig.json, connaisseur/tests/test_alert.py, connaisseur/tests/test_flask_server.py, connaisseur/util.py, helm/templates/env.yaml
Recfatored the alerting feature
=> refactor: refactored alerting

connaisseur/res/config_schema.json, helm/values.yaml, tests/data/config/ext/auth.yaml, tests/data/config/sample_secrets.yaml
config schema for auth required "user" attribute while the actual attribute is "username"
=> fix: auth config schema

connaisseur/flask_server.py
This commit changes the order of the readiness endpoint checking for webhook and sentinel. During normal operations the webhook will be accessible in which case the pod can immediately respond ready. Prior to this commit the sentinel was asked first every time.
Fix #233
=> performance: Fix order of webhook and sentinel probes during readiness probe

docs/validators/notaryv1.md, docs/validators/sigstore_cosign.md
=> docs: add namespace info for validator secrets

README.md
=> docs: remove Helm purge flag from README.md

.github/workflows/cicd.yaml, connaisseur/validators/cosign/cosign_validator.py, connaisseur/validators/interface.py, connaisseur/validators/notaryv1/notary.py, connaisseur/validators/notaryv1/notaryv1_validator.py, connaisseur/validators/static/static_validator.py, connaisseur/validators/validator.py, tests/validators/notaryv1/test_notary.py
=> ci: fix pylint to scan connaisseur dir

.github/actions/k3s-cluster/action.yaml, .github/actions/k8s-version-config/action.yaml
- currently, a [GitHub Marketplace ](https://github.com/marketplace/actions/k3s-with-calico-and-helm) action is used that also adds additional tooling that is not required
- the PR builds a custom k3s cluster without external code or additional tooling
=> ci: use custom k3s cluster

.github/workflows/cicd.yaml, tests/integration/upgrade-integration-test.sh
Fixes no issue
- implements an Connaisseur upgrade integration test that will help highlight breaking changes (for upgrade)
- Connaisseur is installed in the `master` version and then upgraded to the `branch`
- integration tests confirm the proper working of Connaisseur
=> ci: connaisseur upgrade integration test

Makefile, connaisseur/validators/cosign/cosign_validator.py, tests/data/cosign/no_data.txt, tests/data/cosign/wrong_key.txt, tests/validators/cosign/test_cosign_validator.py
Fixes no issue
- updates cosign to v1.3.0
- fixes 1 vulnerabilities introduced via cosign
- some configuration and outputs of cosign were changed and had to be adjusted
=> update: cosign v1.2.1 to v1.3.0

v2.2.0/404.html, v2.2.0/CODE_OF_CONDUCT/index.html, v2.2.0/CONTRIBUTING/index.html, v2.2.0/RELEASING/index.html, v2.2.0/SECURITY/index.html, v2.2.0/adr/ADR-1_bootstrap-sentinel/index.html, v2.2.0/adr/ADR-2_release-management/index.html, v2.2.0/adr/ADR-3_multi_notary_config/index.html, v2.2.0/adr/ADR-4_modular/index.html, v2.2.0/adr/ADR-5_no-more-bootstrap/index.html, v2.2.0/adr/ADR-6_dynamic-config/index.html, v2.2.0/adr/index.html, v2.2.0/basics/index.html, v2.2.0/features/alerting/index.html, v2.2.0/features/automatic_child_approval/index.html, v2.2.0/features/detection_mode/index.html, v2.2.0/features/index.html, v2.2.0/features/namespaced_validation/index.html, v2.2.0/getting_started/index.html, v2.2.0/index.html, v2.2.0/overrides/main.html, v2.2.0/threat_model/index.html, v2.2.0/validators/index.html, v2.2.0/validators/notaryv1/index.html, v2.2.0/validators/notaryv2/index.html, v2.2.0/validators/sigstore_cosign/index.html
=> docs: update announcement of docs on v2.2.0

requirements.txt
Fixes a complaint from safety about aiohttp.
=> fix: update aiohttp

Makefile
=> Update/cosign 1.4.0

Makefile
=> Update/cosign 1.4.1

helm/templates/env.yaml, helm/values.yaml
Add `defaultLogLevel` helm value.
No breaking change.
=> feat: support custom LogLevel

helm/Chart.yaml, helm/values.yaml
Bumps the app version to 2.3.0 and chart version to 1.1.0.
=> update: version bump

v2.2.1/404.html, v2.2.1/CODE_OF_CONDUCT/index.html, v2.2.1/CONTRIBUTING/index.html, v2.2.1/RELEASING/index.html, v2.2.1/SECURITY/index.html, v2.2.1/adr/ADR-1_bootstrap-sentinel/index.html, v2.2.1/adr/ADR-2_release-management/index.html, v2.2.1/adr/ADR-3_multi_notary_config/index.html, v2.2.1/adr/ADR-4_modular/index.html, v2.2.1/adr/ADR-5_no-more-bootstrap/index.html, v2.2.1/adr/ADR-6_dynamic-config/index.html, v2.2.1/adr/ADR-7_wsgi-server/index.html, v2.2.1/adr/index.html, v2.2.1/basics/index.html, v2.2.1/features/alerting/index.html, v2.2.1/features/automatic_child_approval/index.html, v2.2.1/features/detection_mode/index.html, v2.2.1/features/index.html, v2.2.1/features/namespaced_validation/index.html, v2.2.1/getting_started/index.html, v2.2.1/index.html, v2.2.1/overrides/main.html, v2.2.1/threat_model/index.html, v2.2.1/validators/index.html, v2.2.1/validators/notaryv1/index.html, v2.2.1/validators/notaryv2/index.html, v2.2.1/validators/sigstore_cosign/index.html
Fixes no issue
- fix announcement header for the docs of v2.2.1
=> docs: update announcement of docs on v2.2.1

.github/workflows/cicd.yaml
Fixes no issue
- Kubernetes v1.23 is released
- add compatibility tests for v1.23
=> ci: test compatibility with Kubernetes v1.23

helm/values.yaml
=> Fix captialization

.github/workflows/cicd.yaml, .github/workflows/release.yaml, helm/values.yaml, tests/integration/README.md, tests/integration/cause_load.sh, tests/integration/deployments/deployment_i1.yaml, tests/integration/deployments/deployment_i1n1.yaml, tests/integration/deployments/deployment_i1u1.yaml, tests/integration/deployments/deployment_i2.yaml, tests/integration/deployments/deployment_i2i.yaml, tests/integration/deployments/deployment_i2u1-1.yaml, tests/integration/deployments/deployment_i2u1-2.yaml, tests/integration/deployments/deployment_i2u2.yaml, tests/integration/deployments/deployment_i2ui.yaml, tests/integration/deployments/stresstest.yaml, tests/integration/deployments/valid_container_with_unsigned_init_container_image.yml, tests/integration/deployments/valid_init_container.yaml, tests/integration/integration-test.sh, tests/integration/loadtest.yaml.template, tests/integration/upgrade-integration-test.sh, tests/integration/workload-objects/CronJob.yaml, tests/integration/workload-objects/DaemonSet.yaml, tests/integration/workload-objects/Deployment.yaml, tests/integration/workload-objects/Job.yaml, tests/integration/workload-objects/Pod.yaml, tests/integration/workload-objects/ReplicaSet.yaml, tests/integration/workload-objects/ReplicationController.yaml, tests/integration/workload-objects/StatefulSet.yaml
Splits the stress test
Re-enables local integration tests
Removed broken "all" test
Fixes integration test documentation
Improve helm/values.yaml indentation consistency
=> Split stress test and re-enable local integration tests

tests/integration/integration-test.sh, tests/integration/update.yaml
Removes test namespaces after installation during integration test
=> Cleanup test namespaces

.github/workflows/release.yaml, tests/integration/integration-test.sh
- allowlisting for GMS-2021-101 https://github.com/sse-secure-systems/connaisseur/pull/495
- test compatibility with Kubernetes v1.23 https://github.com/sse-secure-systems/connaisseur/pull/429
- ci: fix release pipeline https://github.com/sse-secure-systems/connaisseur/pull/497
- update pytest-asyncio requirement from ~=0.17.0 to ~=0.17.2 https://github.com/sse-secure-systems/connaisseur/pull/490
- update mkdocs-material requirement from ~=8.1.6 to ~=8.1.7 https://github.com/sse-secure-systems/connaisseur/pull/489
- version bump https://github.com/sse-secure-systems/connaisseur/pull/494
- update mkdocs-material requirement from ~=8.1.4 to ~=8.1.6 https://github.com/sse-secure-systems/connaisseur/pull/482
- update jsonschema requirement from ~=4.3.3 to ~=4.4.0 …
=> Release 2.4.0

Makefile
Fixes no issue
update cosign to version 1.5.0
=> update: cosign v1.4.1 to v1.5.0

Makefile, helm/Chart.yaml, helm/values.yaml
Fixes no issue
- update cosign from v1.5.0 to v1.5.1
=> Update/cosign 1.5.1

v2.3.0/404.html, v2.3.0/CODE_OF_CONDUCT/index.html, v2.3.0/CONTRIBUTING/index.html, v2.3.0/RELEASING/index.html, v2.3.0/SECURITY/index.html, v2.3.0/adr/ADR-1_bootstrap-sentinel/index.html, v2.3.0/adr/ADR-2_release-management/index.html, v2.3.0/adr/ADR-3_multi_notary_config/index.html, v2.3.0/adr/ADR-4_modular/index.html, v2.3.0/adr/ADR-5_no-more-bootstrap/index.html, v2.3.0/adr/ADR-6_dynamic-config/index.html, v2.3.0/adr/ADR-7_wsgi-server/index.html, v2.3.0/adr/index.html, v2.3.0/basics/index.html, v2.3.0/features/alerting/index.html, v2.3.0/features/automatic_child_approval/index.html, v2.3.0/features/detection_mode/index.html, v2.3.0/features/index.html, v2.3.0/features/namespaced_validation/index.html, v2.3.0/getting_started/index.html, v2.3.0/index.html, v2.3.0/overrides/main.html, v2.3.0/threat_model/index.html, v2.3.0/validators/index.html, v2.3.0/validators/notaryv1/index.html, v2.3.0/validators/notaryv2/index.html, v2.3.0/validators/sigstore_cosign/index.html
Fixes no issue
- patching the announcement bar of former release
=> docs: update announcement of docs on v2.3.0

v2.4.0/404.html, v2.4.0/CODE_OF_CONDUCT/index.html, v2.4.0/CONTRIBUTING/index.html, v2.4.0/RELEASING/index.html, v2.4.0/SECURITY/index.html, v2.4.0/adr/ADR-1_bootstrap-sentinel/index.html, v2.4.0/adr/ADR-2_release-management/index.html, v2.4.0/adr/ADR-3_multi_notary_config/index.html, v2.4.0/adr/ADR-4_modular/index.html, v2.4.0/adr/ADR-5_no-more-bootstrap/index.html, v2.4.0/adr/ADR-6_dynamic-config/index.html, v2.4.0/adr/ADR-7_wsgi-server/index.html, v2.4.0/adr/index.html, v2.4.0/basics/index.html, v2.4.0/features/alerting/index.html, v2.4.0/features/automatic_child_approval/index.html, v2.4.0/features/detection_mode/index.html, v2.4.0/features/index.html, v2.4.0/features/namespaced_validation/index.html, v2.4.0/getting_started/index.html, v2.4.0/index.html, v2.4.0/overrides/main.html, v2.4.0/threat_model/index.html, v2.4.0/validators/index.html, v2.4.0/validators/notaryv1/index.html, v2.4.0/validators/notaryv2/index.html, v2.4.0/validators/sigstore_cosign/index.html
=> docs: update announcement of docs on v2.4.0

Makefile
Fixes no issue
- updating cosign to latest version
=> update: cosign v1.5.1 to v1.5.2

.github/PULL_REQUEST_TEMPLATE.md
=> docs: fix contributing guide link in pr template

tests/test_logging_wrapper.py
Adds missing tests for the logging wrapper
=> test: added tests for logging wrapper

helm/Chart.yaml, helm/values.yaml
Fixes no issue
* update docker image and helm chart versions
* Chart: v1.3.0
* Image: v2.5.0
=> Update/version 2.5.0

Makefile, connaisseur/validators/cosign/cosign_validator.py, tests/data/cosign/does_not_exist.txt, tests/integration/cases.yaml, tests/validators/cosign/test_cosign_validator.py
Fixes no issue
* update to cosign version 1.6.0
=> Update/cosign 1.6.0

.github/actions/k8s-version-config/action.yaml, .github/workflows/nightly-scans.yaml, tests/integration/integration-test.sh
fixes #527
* make sure nightly scans work and provide a full picture
* example see here: https://github.com/sse-secure-systems/connaisseur/runs/5424795881?check_suite_focus=true
=> ci: fix and improve completeness of nightly scans

requirements_dev.txt
Fixes no issue
* dependabot PRs #594 and #592 fail to run the tests. updates are created manually
=> update: python dev dependencies

Makefile
Fixes no issue
* update cosign to v1.7.1
=> update: cosign v1.6.0 to v1.7.1

Makefile
fixes #642
- update cosign to v1.8.0
=> update: cosign v1.7.2 to v1.8.0

.github/workflows/cicd.yaml
Fixes no issue
previously the helm/values.yaml was shown before install during which the values.yaml is modified. switching order to make sure the end result is shown
=> ci: show the actual config

tests/integration/integration-test.sh
Fixes no issue
the complexity test frequently fails due to timeouts. this is likely to be fixable by granting more resources to the admission controller
=> ci: increase complexity test resources

.github/actions/safety/action.yaml, .github/workflows/cicd.yaml
=> ci: fix safety scanner

Makefile, helm/Chart.yaml, helm/values.yaml
Fixes no issue
- update cosign to `v1.9.0`
- fixes known vulnerabilities
=> update: cosign v1.8.0 to v1.9.0

.github/workflows/cicd.yaml, .github/workflows/nightly-scans.yaml
Fixes no issue
* adding compatibility test with Kubernetes v1.24
=> test: compatibility with k8s v1.24

.github/workflows/cicd.yaml, tests/integration/integration-test.sh, tests/integration/upgrade-integration-test.sh
=> ci: fix webhook unavailable errors

.github/workflows/release.yaml
=> refactor: default github action for release test cluster

.github/workflows/release.yaml, Makefile, connaisseur/validators/cosign/cosign_validator.py, tests/data/cosign/wrong_key.txt
Fixes no issue
- update cosign from v1.9.0 to v1.10.0
=> update: cosign v1.9.0 to v1.10.0

.github/workflows/nightly-scans.yaml
Fixes no issue
- Safety is failing during nightly scans, as the report format was changed
=> ci: fix safety for nightly scan

Makefile
Fixes no issue
- update cosign to version 1.11.1
=> update: cosign v1.11.0 to v1.11.1

Makefile
Fixes no issues
- update cosign dependency to v1.12.1
=> update: cosign v1.11.1 to v1.12.1

.github/workflows/cicd.yaml, .github/workflows/nightly-scans.yaml
Fixes no issue
- add integration tests for kubernetes version 1.25 to ensure compatibility
=> ci: add integration tests for k8s 1.25

.github/workflows/codeql-analysis.yml
Fix permission set of CodeQL job. See https://github.com/sse-secure-systems/connaisseur/actions/runs/3984999938/jobs/6831848598 for successful run of pipeline with this set of permissions.
Fixes #845
=> ci: Fix CodeQL permissions

.github/workflows/.reusable-sca.yml, .github/workflows/cicd.yaml
Fixes no issue
- give trivy necessary permissions to upload sarif file
=> ci: fix trivy permissions

.github/workflows/.reusable-compliance.yml
Fixes no issue
- ossf scorecard cannot run on non-default branches
=> ci: fix ossf scorecard branch pipeline

.github/actions/context/action.yaml
=> ci: fix release

.github/workflows/.reusable-unit-test.yml
=> ci: fix codecov upload

README.md
=> docs: fix nightly-build badge reference

README.md
=> docs: fix nightly-build badge reference (#924)

.github/actions/build/action.yml, .github/actions/context/action.yaml, .github/workflows/.reusable-sast.yml
=> ci: fix unpinned actions

.github/workflows/nightly.yaml
=> ci: remove nightly conditionals

.github/workflows/.reusable-integration-test.yml
=> ci: test k8s v1.26

tests/integration/integration-test.sh
=> Fix typo in test file

docs/features/alerting.md
Fixes alerting documentation that didn't mention the proper keys
=> docs: Correct alerting documentation

.github/actions/build/action.yml, .github/workflows/.reusable-integration-test.yml, Makefile, connaisseur/validators/cosign/cosign_validator.py, docs/validators/sigstore_cosign.md, scripts/get_root_key.py, scripts/upgrade_to_version_3.py, tests/integration/integration-test.sh, tests/integration/update.yaml, tests/validators/cosign/test_cosign_validator.py
updateing cosign to version 2.0.0
Fixes #918
=> update: cosign 2.0.0

tests/integration/integration-test.sh
=> ci: fix release workflow

docs/features/alerting.md, helm/alert_payload_templates/msteams.json
duplicate of #1066 since pipeline won't work.
=> feat: create ms teams alert template

helm/templates/_helpers.tpl, helm/templates/deployment.yaml
=> fix: helm error when setting auth username and password

.github/workflows/cicd.yaml, connaisseur/__main__.py, connaisseur/admission_request.py, connaisseur/flask_application.py, connaisseur/logging.py, docs/migrating_to_version_3.md, requirements.txt, tests/test_admission_request.py, tests/test_flask_application.py, tests/test_logging.py
changes logging format to JSON
Fixes #976
=> refactor: changed logging format to json

docs/RELEASING.md
=> Docs: Fix release documentation

.github/actions/trivy-config/action.yaml, .github/actions/trivy-image/action.yaml
=> update: trivy-action

.github/workflows/.reusable-integration-test.yml, connaisseur/__main__.py, requirements.txt
The changes in https://github.com/sse-secure-systems/connaisseur/pull/1274 tried to fix the memory leak problem by directly using an event loop. This unfortunately caused performance issues, so that the load tests regularly failed. Using nest-asyncio fixed the performance issue.
=> fix: overloaded requests

tests/Dockerfile, tests/Dockerfile.unsigned
=> refactor: Minimize software footprint of Dockerfiles

helm/Chart.yaml
=> update: bump version

.github/workflows/.reusable-integration-test.yml, .github/workflows/cicd.yaml, .github/workflows/nightly-build.yaml, .github/workflows/release.yaml
load integration test often fails. complexity and upgrade are not indicators of a direct issue and might be failing. such non-required tests can/must be skipped in certain situations.
=> ci: skip non-required integration tests

docker/Dockerfile.getRoot
Fixes no issue
getRoot was broken and has been fixed
=> test: fix getRoot utility

docs/basics.md
Fixes no issue
- previously the code blocks were not linked in the docs
- this PR renames the blocks to allow linked code blocks
=> docs: fix code blocks in basics

Makefile, connaisseur/validators/cosign/cosign_validator.py, tests/data/cosign/no_data.txt, tests/data/cosign/notfound_in_tl.txt, tests/data/cosign/wrong_key.txt
Fixes no issue
updating cosing v2.0.0 to v2.2.0
=> update: cosign v2.2.0

docker/Dockerfile, tests/integration/integration-test.sh, tests/integration/update-alerting.yaml
More improvements to integration tests
=> More improvements to integration tests

.github/actions/build/action.yml, connaisseur/logging.py, connaisseur/validators/cosign/cosign_validator.py, connaisseur/validators/notaryv1/notary.py, helm/Chart.yaml, tests/conftest.py, tests/test_exceptions.py, tests/test_flask_application.py, tests/test_logging.py, tests/validators/cosign/test_cosign_validator.py, tests/validators/notaryv1/test_notary.py, tests/validators/notaryv1/test_notaryv1_validator.py, tests/validators/notaryv1/test_trust_data.py
Fixes #1236
Add the `--verbose` flag to Cosign invocations if Connaisseur's log level is set to debug
=> Cosign logging

Makefile, connaisseur/validators/cosign/cosign_validator.py, docs/getting_started.md, docs/requirements_docs.txt, docs/validators/sigstore_cosign.md, requirements.txt, requirements_dev.txt
Update Cosign to version 2.2.1 and minor fixes around its integration
=> Cosign 2.2.1

README.md, docs/README.md, docs/basics.md, docs/features/README.md, docs/features/alerting.md, docs/features/automatic_child_approval.md, docs/features/detection_mode.md, docs/features/namespaced_validation.md, docs/getting_started.md, docs/threat_model.md, docs/validators/notaryv1.md, docs/validators/sigstore_cosign.md, helm/templates/alertconfig.yaml, helm/templates/certificate_webhook-conf.yaml, helm/templates/config-secrets.yaml, helm/templates/config.yaml, helm/templates/deployment.yaml, helm/templates/env.yaml, helm/templates/role.yaml, helm/templates/rolebinding.yaml, helm/templates/service.yaml, helm/templates/serviceaccount.yaml, mkdocs.yml
Fixes no issue
* adds functional labels to kubernetes resources
* facilitates and describes how to deploy Connaisseur via kubernetes manifests
=> feat: add functional labels

tests/test_flask_application.py
Make unit tests offline again!
=> test: Fix unit test to use mocked responses instead of live ones

.github/workflows/release.yaml
=> ci: Fix release with security annotations

tests/integration/Dockerfile.populate_notary, tests/integration/README.md, tests/integration/cleanup.sh, tests/integration/integration-test.sh, tests/integration/run_integration_tests.sh
=> test: fix local integration testing and add script for ease of use

.github/workflows/.reusable-sast.yml
=> ci: continue when kubelinter fails

Makefile
Updates Cosign to version 2.2.2
=> update: Update Cosign to version 2.2.2

.github/actions/build/action.yml
=> update: Update anchore/sbom-action to v0.15.1

docker/Dockerfile.getRoot
Fixes [failing build](https://github.com/sse-secure-systems/connaisseur/actions/runs/7550089900/job/20555149641) of getRoot utility
=> build: Fix build of getRoot utility

connaisseur/validators/notaryv1/notary.py, docker/Dockerfile.getRoot, scripts/get_root_key.py
=> build: Fix Notary call in getRoot utility and improve caching

.github/workflows/.reusable-publish.yml, .github/workflows/publish.yml, .github/workflows/release.yaml
=> ci: add manual publish job

build/Dockerfile
Update to the new alpine `ca-certificates` package.
=> build: update ca-certificates

docs/RELEASING.md
Add a checklist to the release documentation and link to the manual publish job
=> docs: Add release checklist

docs/features/automatic_child_approval.md
Remove reference to config that is not implemented
=> docs: Remove reference to config that is not implemented

.github/workflows/.reusable-sast.yml, Makefile, internal/handler/validation/skip.go, internal/validator/cosignvalidator/cosign_validator.go, internal/validator/notaryv1/notaryv1_validator.go
=> fix: linting issues

.github/workflows/.reusable-cleanup-registry.yml
Apparently, the parameters of the snok/container-retention-policy action changed and we didn't really pay attention. This PR fixes the paramters.
=> ci: Fix parameters for snok/container-retention-policy action

scripts/changelogger.py
=> ci: Improve output and runtime of changelog creation script

.github/workflows/.reusable-cleanup-registry.yml
=> ci: Fix parameter value for container-retention-policy action

.github/actions/trivy-config/action.yaml, .github/actions/trivy-image/action.yaml, .github/workflows/.reusable-cleanup-registry.yml, .github/workflows/.reusable-publish.yml, .github/workflows/.reusable-sca.yml, scripts/changelogger.py
Non-release merge to master to fix current CI failures. No commit contains only application or chart changes.
=> Fix nightlies on master

.github/workflows/.reusable-compliance.yml
=> ci: rework compliance step

.github/workflows/105_sca.yml
Fix the trivy exit code not being correctly set.
=> ci: fix trivy exit code
