.gitignore
connaisseur/__main__.py
helm/certs/gen_certs.sh
helm/templates/secrets.yaml
helm/templates/webhook/webhook.yaml

Kubernetes v1.19 requires subjectAltNames to be present on the TLS certificates or otherwise will break. Even though the TLS config file already added those, an OpenSSL bug prevented them to be actually propagated to the actual certificates.
closes #4

fix: added subjectAltNames to TLS certificates

---

Makefile
README.md
connaisseur/__main__.py
connaisseur/admission_review.py
connaisseur/exceptions.py
connaisseur/flask_server.py
connaisseur/tests/test_admission_review.py
connaisseur/tests/test_exceptions.py
connaisseur/tests/test_mutate.py
helm/templates/env.yaml
helm/values.yaml

The detection mode allows Connaisseur to run in non-strict mode, letting non-compliant images pass, but logging the error. As of Kubernetes version 1.19, a warning is issued to the user (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).

feat: implement detection mode

---

connaisseur/image.py
connaisseur/tests/test_image.py

The regex validation for image names does not allow specifying a port in the registry name. This commit extends the domain_re regex to allow ports.
Relates to #6

fix: allow registry with custom port

---

CONTRIBUTING.md
README.md
SECURITY.md

To facilitate contribution to the project by providing a brief how-to-guide for the technical part, some contribution conventions and guidelines for ensuring quality of the project and finally how to interact with the contributors or report vulnerabilities.
Related discussions in #2 and #7.

docs: add contributing guideline and security policy

---

.github/workflows/cicd.yaml
Makefile
connaisseur/__main__.py
connaisseur/res/root_schema.json
connaisseur/res/snapshot_schema.json
connaisseur/res/targets_schema.json
connaisseur/res/timestamp_schema.json
connaisseur/res/trust_schema.json
connaisseur/tests/data/sample3_targets.json
connaisseur/tests/data/sample3_timestamp.json
connaisseur/tests/data/sample4_targets.json
connaisseur/tests/data/sample5_root.json
connaisseur/tests/data/sample5_targets.json
connaisseur/tests/data/sample5_timestamp.json
connaisseur/tests/data/sample6_root.json
connaisseur/tests/test_image.py
connaisseur/tests/test_trust_data.py
connaisseur/trust_data.py
helm/values.yaml
requirements.txt

The current schemas for trust data validation neither allow timezones with negative offsets nor tags containing dashes. This fixes both and adds additional tests.
Fix #10

fix: extend validation schemas to allow dates across all timezones and all possible tag values

---

CONTRIBUTING.md
README.md
SECURITY.md

The reference to the external documentation of DCT has been added, since it is important for the underlying functionality. The mailto links for reaching out to the team were adjusted to use the .dev domain.

docs: add and adjust external and mailto links

---

setup/README.md

The link for the contributing guidelines in the setup guide was pointing nowhere. Fixed it.

doc: fixed contributing link

---

.github/workflows/cicd.yaml

When scans for bandit and safety fail, no report is uploaded and no usable output shown in the pipeline. This complicates fixing. The changes here fix this issue. To see the changes, check the following github actions:
- jobs failing WITHOUT reports: https://github.com/sse-secure-systems/connaisseur/actions/runs/306138127
- jobs failing WITH reports: https://github.com/sse-secure-systems/connaisseur/actions/runs/319746538

ci: scan reports for failed scans

---

Makefile
helm/templates/env.yaml
helm/values.yaml

Previously we incorrectly stated that a notary host value of null would default to the Docker Hub notary. The actual behavior now matches the stated one.
Fix #13

fix: Default to Docker Hub notary

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Standardizing code of conduct and switching from current berlin code of conduct to github default.

docs: update code of conduct to github default

---

docker/Dockerfile
docker/harden.sh
helm/templates/deployment.yaml

The Connaisseur image is based on an alpine image, which has now been slightly hardened. Furthermore the deployment to Kubernetes is now being controlled by a SecurityContext that is a lot stricter than the default configuration. Also Pods now use the runtime's default seccomp profile instead of none.
Fix: #12

feat: harden image and deploy with kubernetes security context

---

Makefile
connaisseur/notary_api.py
connaisseur/tests/test_notary_api.py
helm/templates/env.yaml
helm/values.yaml
setup/README.md
setup/acr/README.md
setup/signedapp.py
setup/unsignedapp.py

Since the Azure Container Registry has a slightly different API than other notaries, some Connaisseur internals had to be adapted. In addition, there's a guide to integrate the ACR starting differently than the general Kubernetes guide.

docs/feat: Allow and document integration with Azure Container Registry

---

setup/README.md

The sed expression was using '/' for replacement. That is however part of the base64 character set and is therefore replaced with '?'

fix/docs: improve compatibility of sed expression to set root pub key

---

setup/README.md

Added the fact that Connaisseur has been tested with a Google Kubernetes Engine cluster

docs: Tested compatibility with Google Kubernetes Engine

---

adr/ADR-1_connaisseur-bootstrap-sentinel.md
adr/README.md

Adds folder for Architecture Decision Records with an explaination of why we use them. Adds first ADR regarding the use of the connaisseur-bootstrap-sentinel Pod.

docs: Architecture Decision Record regarding Sentinel

---

setup/README.md
setup/acr/README.md

Docker does not allow usage of capital letters in image names and repos. This seems to also cause problems with DCT.

docs: use small caps for repo and image names

---

CONTRIBUTING.md

The contributing lacked instructions how to build connaisseur locally for testing.

docs: update contributing guide for local setup

---

setup/README.md

Documented the fact that Connaisseur works with K3s and kind.
Fix #27

docs: Document compatibility with K3s and kind

---

.github/workflows/cicd.yaml
connaisseur/tests/test_notary_api.py

Previously, we claimed to want to format code with black prior to pushing. However, we regularly introduced code that was not formatted properly. This introduces a CI check to ensure pipeline failure if autoformatting would change the code.

ci: Add check for formatting

---

.github/workflows/cicd.yaml
CONTRIBUTING.md
Makefile
connaisseur/tests/integration/integration-test.sh
connaisseur/tests/integration/update-config.yaml

Add integration test with KinD cluster in Github Actions. Tests building of docker images, installing Connaisseur, rejecting unsigned image, rejecting image signed under different key, accepting signed image and uninstallation.
Fix #25

ci/test: Add integration test

---

connaisseur/mutate.py
connaisseur/tests/integration/integration-test.sh
connaisseur/tests/integration/valid_container_with_unsigned_init_container_image.yml
connaisseur/tests/test_mutate.py
helm/values.yaml

Currently, Connaisseur only validates the images referenced 'containers'. This adds validation for images referenced in 'initContainers'.

fix: validate images of initContainers

---

Makefile
helm/templates/bootstrap-sentinel.yaml
helm/values.yaml
setup/README.md

Previously Connaisseur's bootstrap sentinel had a fixed timeout of 30s, which could cause problems on clusters with low bandwidth the first time they pull the Connaisseur image. This PR allows configuration of the timeout and increases its default value to 60s.
Fix #46

feat: Allow configuration of bootstrap sentinel timeout and increase default

---

.github/workflows/cicd.yaml
.github/workflows/release.yaml
Makefile
adr/ADR-2_release-management.md
connaisseur/tests/integration/integration-test.sh
connaisseur/tests/integration/update-config.yaml
setup/README.md

Previously we had no automatic releases. Now a delegation key is used to sign the images, which will subsequently be pushed to the repository with a technical user. Images will be released for each new tag on the master branch. It is ensured that the tag matches the versions defined in both the Makefile and the helm deployment.
TODO:
Discussion:
Idea is to have a PR to master that increments version number. After merge, one needs to `git tag` the new master commit and push the tag. Then the release pipeline would run
In my mind the PR would be dedicated and only increment the version and add to a Changelog.md
Are you fine with releasing this way? Do we want to do something different? Do you see potential problems / areas to improve?

 ci/docs: Release concept for Connaisseur image and release check on new tagged commit on master branch

---

connaisseur/flask_server.py
connaisseur/mutate.py
connaisseur/tests/test_flask_server.py
connaisseur/tests/test_kube_api.py
connaisseur/tests/test_notary_api.py
helm/values.yaml

Previously the Connaisseur logger may have failed to properly log invalid requests. Increase test coverage for flask server. Prevent some tests from leaking environment variables beyond their scope.

fix/test: Fix handling of invalid requests, increase test coverage

---

.dockerignore
.github/workflows/cicd.yaml
.gitignore
CONTRIBUTING.md
docker/Dockerfile
docker/Dockerfile.hook
requirements.txt
requirements_dev.txt

Originally, the Connaisseur docker image is built in multiple later steps of the pipeline. This causes code duplication, maintenance increase, unintuitive failing and unnecessary ci run time.
Fixes #54

ci: add build step

---

Makefile
adr/ADR-1_connaisseur-bootstrap-sentinel.md
helm/templates/bootstrap-sentinel.yaml
helm/values.yaml
setup/README.md

Currently, 'helm install' does not only not reveal much information about the progress but also does not  proceed anymore as soon as the sentinel has completed. Thus, in case the sentinel times out without connaisseur being ready, the last 4 minutes waiting for the helm timeout are wasted.

fix: Add output during installation and increase sentinel timeout

---

.github/workflows/cicd.yaml
.github/workflows/release.yaml
Makefile
connaisseur/tests/integration/update-config.yaml
helm/templates/webhook/job.yaml
helm/values.yaml

Minor changes to the helm-hook-image could break prvious versions of connaisseur, which is why versioning is introduced to circumvent this.
fixes #67

build: Added versioning to helm-hook-image

---

.github/workflows/cicd.yaml

Security checks are run after quality checks. This is parallelized since there is no real dependency

ci: parallelize source code scans

---

.github/workflows/release.yaml

Previously we used the GITHUB_REF variable set during the execution of of Github Actions to get to the current tag, which failed if tagging was done on prior to the push/on a different branch. Now we use the information contained in the git repository that is checked out anyway. Additionally the release pipeline previously also ran for any new commit on master (without a new tag being present) and now runs only for tags in potentially any branch (which is fine, as the release pipeline does no privileged action).

ci: Improve tag detection during release

---

.github/workflows/cicd.yaml
connaisseur/notary_api.py
connaisseur/validate.py
helm/values.yaml

in the special case, that delegations haven been added to an imgae repository, but no signatures were created using said delegations, the delegations appear in the targets JSON, but the actual delegation JSON files don't exist yet. Previously connaisseur assumed them to be present if they are in the targets JSON. This was changed to use the targets in the targets JSON file, instead of the missing delegation JSON files.

fix: missing delegation files

---

.github/workflows/dockerhub-check.yml
README.md
connaisseur/tests/integration/integration-test.sh
connaisseur/tests/integration/update.yaml
connaisseur/tests/integration/valid_container_with_unsigned_init_container_image.yml
connaisseur/validate.py
setup/Dockerfile.unsigned
setup/README.md

Previously, we had test images at docker.io/connytest/testimage but decided we wanted to have have the securesystems repository instead. This PR follows up on that decision.
Fix #41

docs/test: Move test images into securesystems DockerHub repository

---

connaisseur/crypto.py
connaisseur/notary_api.py
connaisseur/tests/test_mutate.py
connaisseur/tests/test_trust_data.py
connaisseur/tests/test_validate.py
connaisseur/trust_data.py
connaisseur/validate.py
docs/validation.md

This PR documents the existing validation procedure employed by Connaisseur. In addition, it adds some test cases for all supported and one unsupported Kubernetes resource, tests more invalid trust data and checks the combination of valid and invalid delegations alongside each other. Also typos

docs/test: Documentation for image validation, improve validation test coverage

---

.github/workflows/nightly-scans.yaml

This PR adds a scheduled nightly scan via Github Actions. Both Safety and Trivy will be run to ensure the current code on master is free of known vulnerabilites
Fix #66

ci: Add nightly scans with safety and trivy

---

connaisseur/key_store.py
connaisseur/mutate.py
connaisseur/notary_api.py
connaisseur/policy.py
connaisseur/trust_data.py
requirements_dev.txt

Pylint 2.7.0 includes a fix for vulnerable regular expressions in 'pyreverse'.

hotfix/ci: updated pylint

---

SECURITY.md
connaisseur/tests/test_keystore.py
connaisseur/tests/test_mutate.py
connaisseur/tests/test_notary_api.py
connaisseur/tests/test_trust_data.py
connaisseur/tests/test_validate.py
connaisseur/trust_data.py
connaisseur/validate.py
helm/values.yaml

Previously, Connaisseur accepted all trust data files at first and then validated them. This was not an immediate security issue, since the root key could not be overwritten and since the KeyStore is write-once, so keys will only be used after they have been validated. However, Connaisseur would have pulled all delegations in a malicious targets.json without prior validation, which would have allowed an attacker to specify many non-existant delegations, potentially causing a denial of service. This PR fixes the issue by first validating and then processing the trust data files. In addition, the way Connaisseur previously validated trust data files would have allowed an attacker that compromised the long-term snapshot key to mount freeze attacks (i.e. ignoring the validation via timestamp …

Fix/refactor: Refactor validate method to not use non-validated data

---

helm/templates/namespace.yaml
helm/templates/webhook/_webhook.tpl
helm/templates/webhook/webhook.yaml
helm/values.yaml

This commit aims to add the feature to enable the Connaiseur
Webhook validation in *some* K8s namespaces and not the whole
cluster.
This is done by adding a variable in the `values.yaml` file
called `targetNamespaces`, that contains a list of namespace names.
The webhook will then be used by container creations ONLY in these
namespaces.
In case the names in the list are not available as namespaces,
they are auto-created.
Finally, the default value of `['*']`, deploys the default behavior -
validating all the cluster containers.

Enable Per-Namespace verification

---

README.md
setup/README.md

the issue was introduced in #79 when all testimages were moved to `docker.io/securesystemsengineering/testimage` but only the public key for integration tests was changed. Consequently, demo and other setup guides would not work anymore

docs/fix: adjust public keys in READMEs to DockerHub Repo

---

.github/workflows/cicd.yaml

The code coverage silently fails, since the python:slim image doesn't contain git and curl for it to function. This is fixed.

ci: codecov fix

---

.github/workflows/cicd.yaml
.github/workflows/release.yaml
connaisseur/tests/integration/namespaced-integration-test.sh
connaisseur/tests/integration/namespaced-update.yaml
helm/values.yaml

This commit adds an integration test for the namespaced verification behaviour of Connaisseur.
Fix #103

ci/test: Test Connaisseur verification with target namespace

---

.dockerignore

Previously, we erronously built with code coverage files and the python cache if it was present on the developer's machine

fix: Remove development files from image

---

connaisseur/tests/integration/alerting/app/alert_checker.py

This commit removes the debug option from the flask server run during the integration test as it is not necessary and generates a security warning

ci/test: Remove debug option from integration test server

---

CONTRIBUTING.md
README.md
setup/README.md

GitHub Discussions can help us to better interact with the community beyond simple issues for bugs and feature requests. This commit makes this communication option transparent to our users.

docs: add information on github discussions

---

.github/workflows/cicd.yaml
.github/workflows/dockerhub-check.yml
.github/workflows/release.yaml
Makefile
README.md
connaisseur/crypto.py
connaisseur/exceptions.py
connaisseur/mutate.py
connaisseur/sigstore_validator.py
connaisseur/tests/data/cosign_error_no_data.txt
connaisseur/tests/data/cosign_error_wrong_key.txt
connaisseur/tests/integration/cosign-integration-test.sh
connaisseur/tests/integration/cosign-update.yaml
connaisseur/tests/test_crypto.py
connaisseur/tests/test_exceptions.py
connaisseur/tests/test_sigstore_validator.py
connaisseur/tests/test_validate.py
connaisseur/validate.py
docker/Dockerfile
helm/templates/env.yaml
helm/values.yaml
requirements_dev.txt
setup/COSIGN.md

[sigstore](https://github.com/sigstore) project for software supply chain transparency and [sigstore/cosign](https://github.com/sigstore/cosign) for container signing and verification offer an alternative to Notary v1 and Notary v2. This is an initial tentative integration into Connaisseur.
Currently a rough first hack to get `cosign` on board and allow playing around with it as an experimental feature. Important next steps:
- move signed digest identification into module
- only use cosign when configured
- fix parsing of stdout return
- rewrite the popen echo part properly
In case you want to test it, you will have to build the Conny image locally. To generate a key pair and sign your test image:
```
cosign generate-key-pair
cosign sign -key cosign.key <reponame>/<imagename>:signed
``` …

feat: sigstore/cosign support

---

.github/workflows/cicd.yaml

Set the integration test matrix to fail slow. Will allow inspecting the outcome of all integration tests.

ci: fail slow on integration tests

---

connaisseur/alert.py
connaisseur/tests/test_alert.py

Do not check alert config on hook image to ensure `make uninstall` is working

fix: alert configuration error on hook image

---

connaisseur/flask_server.py
tests/test_flask_server.py

After installing connaisseur the health probe will fail after some time though it only returns true it runs health checks on validators that will not influence the health status but be logged if unhealthy. In case the health checks for the validators take too long, the pod health probe timeouts and the pod is considered unhealthy. Validator health checks are now separated from the pod health.

fix: health probe fails after some time

---

helm/templates/webhook/webhook.yaml

👋 
I had troubles deploying a terraform workflow, that executed a server side dry-run:
```txt
...: patch failed 'application/strategic-merge-patch+json': admission webhook "connaisseur-svc.connaisseur.svc" does not support dry run
```
Reading through these [docs](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#side-effects), I've updated the webhook config to have `sideEffects: None` (defaults to Unknown), and this solved the problem.
I'm not sure if `None` is the correct value, but I don't think in the case of Connaisseur it is a problem.

Set side effect to None so server-side dry run is possible

---

.github/actions/integration-test/action.yaml
.github/workflows/cicd.yaml
connaisseur/validators/notaryv1/notary.py
connaisseur/validators/notaryv1/notaryv1_validator.py
docker/Dockerfile
requirements.txt
requirements_dev.txt
tests/conftest.py
tests/test_flask_server.py
tests/validators/notaryv1/test_notary.py
tests/validators/notaryv1/test_notaryv1_validator.py

A major amount of connaisseur's runtime (for nv1 validation) is wasted with receiving the trust data from the notary server. To reduce this time, the requests have been parallelized.

refactor(nv1): parallel trust data request

---

connaisseur/validators/cosign/cosign_validator.py
helm/templates/_helpers.tpl

cosign authentication is added by mounting a docker config.json under the `/app/connaisseur-config/{validator}/.docker/config.json`. Cosign checks in the home directory for `.docker/config.json` and consequently, the `HOME` env var for the subprocess call for cosign is also adjusted to the validator dir.

feat: add cosign authentication via k8s dockerconfigjson

---

.github/workflows/nightly-scans.yaml
README.md
docker/Dockerfile.getRoot
scripts/get_root_key.py

Previously, building the get-root utility failed due to a new requirement of the cryptography package, that now requires a rust compiler on alpine-based distributions. This commit adds the rust compiler to fix it. Also, the utility was out of sync with the changes to the notary interface, which is also rectified by this commit. Lastly, it fixes a faulty reference in the docs

Fix get root utility

---

Makefile
helm/crds/imagepolicy.yaml

Previously `make annihilate` didn't delete the image policy CRD and the connaisseur namespace. Now it does, which allows to freshly reinstall connaisseur eventhough changes to the image policies format were made.

refactor(Makefile): make annihilate deletes everything

---

.github/actions/integration-test/action.yaml
.github/workflows/cicd.yaml
.github/workflows/release.yaml

Fixed the release workflow, so it actually can load the Connaisseur images from DockerHub.

fix: image loading for release workflow (#192)

---

.github/workflows/nightly-scans.yaml

With the new dependencies from asyncio, the nightly scans fail as they run on an alpine based container which can't install the dependencies without special enviornment variables. This was fix by switching to a debian based container.

fix: nightly scans

---

.github/workflows/nightly-scans.yaml

With the new dependencies from asyncio, the nightly scans fail as they run on an alpine based container which can't install the dependencies without special enviornment variables. This was fix by switching to a debian based container.

fix: nightly scans (#195)

---

connaisseur/validators/notaryv1/notary.py
tests/validators/notaryv1/test_notary.py

By removing the heath check before each acquisition of a trust data file, the run time of connaisseur speeds up dramatically.

refactor: faster trust data

---

docker/Dockerfile
docker/release-cosign.pub

requires:
significantly improves build speed :rocket:

build: get signed cosign binary

---

.github/workflows/cicd.yaml
.kube-linter/config.yaml
docs/RELEASING.md
helm/Chart.yaml
helm/templates/_helpers.tpl
helm/templates/bootstrap-sentinel.yaml
helm/templates/webhook/job.yaml
helm/values.yaml

KubeLinter is a SAST tool to scan Kubernetes YAML and Helm Charts: https://github.com/stackrox/kube-linter
The documentation can be found here: https://docs.kubelinter.io/
The following questions arise:
* KL is currently in early development and we have to see whether that is okay for us
* Check the findings
* Does it provide value? Yes. It actually found bugs in our charts.
Open Questions if we want to proceed:
To see the results, check the GH Action.
**For Review:**
- Please closely review and extend security settings. We should configure this very rigorously.
- Should we bump *MINOR* Version?

ci:add kube-linter

---

tests/integration/cosign-integration-test.sh
tests/integration/integration-test.sh
tests/integration/namespaced-integration-test.sh
tests/integration/preconfig-integration-test.sh
tests/integration/valid_container_with_unsigned_init_container_image.yml
tests/integration/valid_init_container.yaml

This commit adds the connaisseur label to all resources created during a successful integration test, such that they can be deleted with make annihilate regardless of namespace

tests: Add labels to integration test resources

---

.github/dependabot.yml

dependabot is already checking for all requirements.txt including the `docs` subdirectory which currently causes duplicate update PRs

ci: drop redundant dependabot configuration

---

helm/templates/podsecuritypolicy.yaml
helm/templates/role.yaml
helm/templates/webhook/role.yaml
helm/values.yaml

Installing Connaisseur on a Kubernetes cluster that has the
PodSecurityPolicy feature enabled is not working.
This PR fixes this issue by adding the option on Helm chart to take into
acccount the PSP feature.
Fixes: #258
Signed-off-by: Youssef Azrak <yazrak.tech@gmail.com>

Add PodSecurityPolicy to the Helm manifests

---

connaisseur/validators/notaryv1/notary.py

To enable the `pylint` update suggested by dependabot we need to satisy a newly introduce linting rule.

fix: satisfy new pylint rule

---

helm/values.yaml
tests/integration/deployment-update.yaml

in the docs, we note that validator names should be "lower case alphanumeric or -" which is required as the names are used for volume names in case of cosign authentication. we should be consistent throughout the pre-config.

fix: use compliant/consistent validator names

---

README.md
connaisseur/flask_server.py
docs/README.md
docs/basics.md
docs/features/README.md
docs/features/automatic_child_approval.md
helm/templates/certificate_webhook-conf.yaml
helm/templates/env.yaml
helm/values.yaml
mkdocs.yml

automatic child approval was introduced for efficiency and explicitness. it however causes pods that become untrusted to not be blocked when restarting. switching to only pod validation and dropping ACA.
fixes #244

feat: improve automatic child approval

---

helm/templates/deployment.yaml
helm/values.yaml

After this small fix connaisseur runs as a normal helm deployment inside OKD / OpenShift 4 (tested with OKd 4.7).
Only set the value: `openshift: true` in your value.yaml file.
Openshift and OKD are using secure container by default (randomized user and group execution). So we have to disable the fixed user and group setting. This let OpenShift decide ;-)

Openshift fix

---

connaisseur/image.py
tests/test_image.py

Only tags can have uppercase characters.
Excluding tags from lowercase comparison.

Allow CAPS in image tag

---

connaisseur/alert.py
connaisseur/flask_server.py
tests/conftest.py
tests/data/sample_admission_requests/ad_request_invalid.json
tests/test_flask_server.py

This commit adds graceful handling to Connaisseur receiving syntactically invalid admission requests, such that e.g. an alert can be sent out that admission failed

fix: Handle invalid admission requests

---

.github/workflows/cicd.yaml
connaisseur/workload_object.py
helm/values.yaml
tests/integration/workload-objects-integration-test.sh
tests/integration/workload-objects/CronJob.yaml
tests/integration/workload-objects/DaemonSet.yaml
tests/integration/workload-objects/Deployment.yaml
tests/integration/workload-objects/Job.yaml
tests/integration/workload-objects/Pod.yaml
tests/integration/workload-objects/ReplicaSet.yaml
tests/integration/workload-objects/ReplicationController.yaml
tests/integration/workload-objects/StatefulSet.yaml

fixes #382 
- adds integration tests for workload objects and api versions for each Kubernetes version
- fixes currently unsupported api versions

fix: support api versions for k8s workloadobjects, add tests

---

mkdocs.yml

Fixes no issue
- adds ADR-7 to the docs page
- minor change without any implications

docs: add ADR-7

---

tests/integration/upgrade-integration-test.sh

Fixes no issue
- randomizes the pod names to avoid having to delete pods between tests on `master` and test branch

ci: speedup upgrade integration test

---

connaisseur/validators/cosign/cosign_validator.py
tests/validators/cosign/test_cosign_validator.py

Fixes no issue
- several different types of keys (ecdsa, rsa) and references (email, kms) are being added to cosign and integrated for connaisseur
- the handling and identification of key type is being refactored to improve extension

Refactor: cosign key types

---

connaisseur/res/config_schema.json
tests/data/config/err6.yaml
tests/data/config/sample_config.yaml
tests/test_config.py

The configration pattern no longer blocks localhost as a valid notary host path and also allows port specifications.
fixes #445

fix: allow localhost as notary server

---

connaisseur/res/config_schema.json
connaisseur/validators/cosign/cosign_validator.py
docs/validators/sigstore_cosign.md
helm/templates/_helpers.tpl
helm/templates/config-secrets.yaml
helm/templates/config.yaml
helm/templates/deployment.yaml

For cosign validators, a new field (`cert`) has been added so that cosign signatures can be validated against registries with selfsigned certificates.
fixes #324

feat: cosign private registry

---

helm/templates/deployment.yaml
helm/values.yaml

Allow the deployment manifests to use a secret to pull images.
Fixes #

feat: implement imagePullSecrets for private container registries

---

helm/templates/deployment.yaml
helm/values.yaml

It is common practice for helm charts to provide "extra configuration" abilities to tweak the kubernetes deployment.
This PR provides a generic approach to bring extra configuration such as sidecar containers and extra volumes.
This make it easier to fixes https://github.com/sse-secure-systems/connaisseur/issues/390
For example, with only helm values on the user side, this allow to configure a sidecar container to run a ECR token refresher.
This is another alternative of the cronjob solution (https://github.com/sse-secure-systems/connaisseur/discussions/411) to address the private ECR (short-life) token refresh need, without pod restarts, thanks to the use of sidecar container.
User config example:
```
deployment:
extraVolumes:
- name: refresher-vol
emptyDir: {}
extraVolumeMounts:
- …
```

feat: support extra configuration in helm chart

---

helm/Chart.yaml
helm/values.yaml

Version bump to `2.4.0` (chart `1.2.0`)

update: version bump

---

.github/workflows/release.yaml
tests/integration/integration-test.sh

Fixes the release pipeline.
The `ImagePullPolicy` for the release pipeline was accedentially set to `Never`, thus no image could be loaded. This was fixed.

ci: fix release pipeline

---

helm/templates/role.yaml

"replicacontrollers" is not a valid kubernetes object.
Authors probably meant "replicationcontrollers".
In my connaisseur pods, I see error logs such as:
"requests.exceptions.HTTPError: 403 Client Error: Forbidden" for replicationcontrollers api calls.
After editing clusterrole connaisseur-role, replacing "replicacontrollers" with "replicationcontrollers", and doing a rolling restart, those errors msg went away.

fix: corrected typo in ClusterRole helm template

---

connaisseur/workload_object.py

Connaisseur is making invalid API calls when checking for parent resource, when the parent resource is of type pod.
Fixes #513 
Adds rest_path variable that takes either following values:
- "api" if the apiVersion is "v1"
- "apis" otherwise
... to make sure the proper API call is made

fix: updated REST path for core api group

---

docker/Dockerfile

Fixes #
Address vulnerabilities which require an upgrade of `ca-certificates` which is only available in debian bullseye-slim. Upgrading to debian bullseye-slim requires an upgrade of wget.

update: debian bullseye, ca-certificates, wget

---

scripts/changelogger.py

Should the changelogger find a non sematic commit, it previously crashed and could only run should the commit be reworded, resulting in a rebase of develop. Instead the changelogger has been changed to work with non semantic commits, giving a warning should one appear.

ci: fix changelogger for non-semantic commits

---

README.md
connaisseur/flask_application.py
docs/README.md
docs/features/metrics.md
helm/values.yaml
mkdocs.yml
requirements.txt
tests/test_flask_application.py

Introduces simple metrics for Flask application using prometheus-flask-exporter for mutate endpoints. The metrics are available from the /metrics endpoint.
It also introduces the possibility to specify a different port for the mutating webhook based on the service port.
- [-] Extended README/Documentation (if necessary)

feat: prometheus metrics

---

v2.1.1/404.html
v2.1.1/CODE_OF_CONDUCT/index.html
v2.1.1/CONTRIBUTING/index.html
v2.1.1/RELEASING/index.html
v2.1.1/SECURITY/index.html
v2.1.1/adr/ADR-1_bootstrap-sentinel/index.html
v2.1.1/adr/ADR-2_release-management/index.html
v2.1.1/adr/ADR-3_multi_notary_config/index.html
v2.1.1/adr/ADR-4_modular/index.html
v2.1.1/adr/index.html
v2.1.1/basics/index.html
v2.1.1/features/alerting/index.html
v2.1.1/features/detection_mode/index.html
v2.1.1/features/index.html
v2.1.1/features/namespaced_validation/index.html
v2.1.1/getting_started/index.html
v2.1.1/index.html
v2.1.1/threat_model/index.html
v2.1.1/validators/index.html
v2.1.1/validators/notaryv1/index.html
v2.1.1/validators/notaryv2/index.html
v2.1.1/validators/sigstore_cosign/index.html

Fixes no issue
- switch all version 2.1.1 announcements to the new outdated block
- testing on version 2.1.1

docs: update announcement of docs on v2.1.1 to outdated scheme

---

tests/integration/integration-test.sh

As the actual update of the config values happens in its own bash function, the `IPP` variable is no longer set when performing the values.yaml update resulting in an empty value in the yaml file (`imagePullPolicy: ""`).
Fixes #

test: fix unset variable in preconfig integration test

---

connaisseur/logging_wrapper.py

In INFO loglevel, the application healthz endpoints prints lot of logs (because of K8s live/ready-ness) which make hard to read the logs and consume logging storage.
A solution would be to disable the INFO loglevel, but this hides the genuine logs such as image verification operations.
Some flask module suggest to disable the logs on these endpoints, for example: https://pypi.org/project/flask-healthz/, using `no_log` option.
This PR changes the loglevel of the HTTP requests handled by the healthz endpoints to DEBUG, to avoid cluttering the web log files with automated requests.

feat: silent healthz endpoints logging

---

connaisseur/res/config_schema.json
connaisseur/validators/cosign/cosign_validator.py
docs/validators/sigstore_cosign.md
tests/validators/cosign/test_cosign_validator.py

Fixes #390
Add configuration option `k8s_keychain` for `cosign` validator that will pass the flag `--k8s-keychain` to `cosign` when set to true. This allows `cosign` to pick up registry credentials from the environment (see https://github.com/sigstore/cosign/pull/972 for details)

feat: Support cosign --k8s-keychain flag

---

docs/basics.md
helm/templates/certificate_webhook-conf.yaml
helm/values.yaml

Add a value in the Helm chart to set `reinvocationPolicy` of `MutatingWebhookConfiguration`
It should be possible to set `reinvocationPolicy` (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy) for the MutatingWebhookConfiguration resource. 
My use case is:
- I want to make sure that only images from my private registry (which are signed) are used in my cluster
- Thus, for public images, I pull them, sign and then push them to my private registry
- I use `kyverno` to mutate all public images to my private images (e.g. `bitnami/bitnami-shell:10-debian-10-r99` become `my.private.registry/bitnami/bitnami-shell:10-debian-10-r99`
- So, I need `reinvocationPolicy: IfNeeded` to let Connaisseur reevaluate the request after it was mutated …

feat: add reinvocationPolicy option

---

.github/workflows/cicd.yaml
.github/workflows/release.yaml

Expose k8s logs on failure of integration test
We can't introspect the deployment during a CI run and if it fails with unknown error it is hard to debug.
This commit adds k8s logs of the deployment to the CI output in case the integration test fails.
See e.g. https://github.com/sse-secure-systems/connaisseur/runs/5245683641?check_suite_focus=true for output with this change

Expose k8s logs on failure

---

connaisseur/validators/notaryv1/notary.py

Fixes no issue
* it seems the content type for auth.docker.io/token was unexpectedly changed from application/json to text/plain which causes the response parsing to json to fail. the content type check is disabled
* for more details: #566

fix: disable aiohttp content type check

---

tests/integration/integration-test.sh

Fixes no issue
* `helm/values.yaml` is updated during integration tests
* this is specifically problematic in local integration tests and may cause problems in CI tests
* backup is created at begin of integration test and played back in the end

test: reset values.yaml after test

---

.github/workflows/cicd.yaml
.github/workflows/dockerhub-check.yml
.github/workflows/release.yaml
connaisseur/validators/cosign/cosign_validator.py
docs/validators/sigstore_cosign.md
tests/integration/cases.yaml
tests/integration/integration-test.sh
tests/integration/update.yaml
tests/validators/cosign/test_cosign_validator.py

Fixes #375
- a container image can be signed by multiple signers using different keys
- this feature enables validation against all, a threshold number of or specific required trust roots of a validator
- concurrent processing of signatures via asyncio is currently blocked by a asyncio bug
- [Stackoverflow discussion](https://stackoverflow.com/questions/70624413/how-to-read-from-dev-stdin-with-asyncio-create-subprocess-exec)
- [Python bug report](https://bugs.python.org/issue46364)
- concurrency is (for now) implemented via [`concurrent.futures`](https://docs.python.org/3/library/concurrent.futures.html)
- futures yield a significant speedup as shown below
- once the asyncio bug is fixed, both should be benchmarked again
```bash
$ time k run unsigned …
```

feat: multi-signer support for cosign

---

connaisseur/validators/cosign/cosign_validator.py
helm/Chart.yaml
helm/values.yaml

Fixes #575 
* in `v2.5.0` handling of env vars for registry authentication of the cosign validator was modified
* a bug was introduced by which no env vars were set at all
* this caused cosign registry authentication to fail as described in #575 and #573

fix: broken cosign validator authentication for registries

---

connaisseur/validators/cosign/cosign_validator.py
docs/requirements_docs.txt
helm/Chart.yaml
helm/values.yaml
requirements_dev.txt

This Release mainly fixes a bug (#575) in cosign validator authentication to the registry that was introduced in `v2.5.0` (#428): #576 
---
- broken cosign authentication for registries #576
- update mkdocs-material requirement from ~=8.2.4 to ~=8.2.5 #574
- update pytest-asyncio requirement from ~=0.18.1 to ~=0.18.2 #569
- update mkdocs-material requirement from ~=8.2.3 to ~=8.2.4 #568

Release 2.5.1

---

docs/basics.md
docs/validators/sigstore_cosign.md

Hey guys,
This PR clarifies the process of generating / supplying registry secrets for cosign to verify images in private repositories. It's the result of some trial-and-error and debugging efforts today!

[Docs] Add clarity re generating registry credential secrets

---

.github/workflows/dockerhub-check.yml

Fixes no issue
* currently the `dockerhub-check` job only pulls the most recent Connaisseur image
* this PR makes sure all Connaisseur image versions remain available

ci: frequently pull all connaisseur versions

---

docs/validators/sigstore_cosign.md

Fixes no issue
- while current docs work for connaisseur, secret cannot be used as imagePullSecret

docs: fix create image pull secret command

---

connaisseur/validators/cosign/cosign_validator.py
helm/Chart.yaml
helm/values.yaml
tests/validators/cosign/test_cosign_validator.py

Fixes #583
* it seems that as of v2.5.0 digest confusion can occur
* a referenced image gets the digest of another image assigned and admission request is patched accordingly
* causes deployments potentially falsely allowed, but failing due to broken request patching
* the root issue appears to be unexpectatly related to updating a class variable inside concurrent futures / asyncio
* the class variable is removed and inputs are passed into the concurrent tasks, results returned and then used to update the resuts

fix: digest confusion at high load

---

connaisseur/workload_object.py
tests/data/sample_admission_requests/ad_request_pods_unknownparent.json
tests/test_workload_object.py

Fixes #582
* Per default, Connaisseur checks the parent resource of a k8s object as part of automatic child approval.
* This fails when creating a workload object from custom resource definitions (CRDs) as the API group and thus the structure is not known.
* This is fixed by excluding the parent check for unknown API groups.

fix: exclude k8s CRDs from parent resource check

---

requirements.txt

In light of #620 we pinned a transitive dependency to fix incompatibility introduced by a breaking change in said transitive dependency. While being a reasonable quick fix at the time, it imposes undue limits on our dependency. Thus this commit removes the pinning of the transitive dependency and should they again break (the transitive dependency took notice and the dependency took steps to mitigate), we may need to reeavluate the dependency as a whole instead of pinning dependencies that are not ours to pin.

build: Remove transitive dependency pinning

---

.github/workflows/cicd.yaml
.github/workflows/release.yaml
Makefile
helm/Chart.yaml
helm/templates/_helpers.tpl
helm/values.yaml
tests/integration/integration-test.sh

Fixes #724 
As noted in #724 the installation in a different namespace fails as the TLS certificate certificate is looked up in the wrong namespace. This merge request fixes this and adds a test case to the integration test to check we don't run into this again in the future.

Fix installation in other namespace

---

.github/workflows/nightly-scans.yaml
Makefile
docs/requirements_docs.txt
helm/Chart.yaml
helm/values.yaml
requirements.txt
requirements_dev.txt

just fixes and updates.
- Fix safety for nightly scan https://github.com/sse-secure-systems/connaisseur/pull/732
- Update jsonschema requirement from ~=4.9.1 to ~=4.12.1 https://github.com/sse-secure-systems/connaisseur/pull/756
- Cosign v1.10.0 to v1.11.0 https://github.com/sse-secure-systems/connaisseur/pull/757
- Update mkdocs-material requirement from ~=8.3.9 to ~=8.4.0 https://github.com/sse-secure-systems/connaisseur/pull/750
- Update setuptools requirement from ~=64.0.1 to ~=65.1.0 https://github.com/sse-secure-systems/connaisseur/pull/755
- Update setuptools requirement from ~=63.4.1 to ~=64.0.1 https://github.com/sse-secure-systems/connaisseur/pull/747
- Update pytz requirement from ~=2022.1 to ~=2022.2 https://github.com/sse-secure-systems/connaisseur/pull/748
- Update flask …

Release v2.6.3

---

.github/workflows/cicd.yaml
.github/workflows/nightly-scans.yaml
helm/Chart.yaml
helm/values.yaml

Fixes no issue
- changes from deprecated ubuntu `18.04` runners to `latest`

ci: always use ubuntu-latest runners

---

.github/workflows/cicd.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/dockerhub-check.yml
.github/workflows/docs-dev.yaml
.github/workflows/docs.yaml
.github/workflows/nightly-scans.yaml
.github/workflows/release.yaml

Previously any action and job ran with full read/write privileges as some jobs (docs) need write access. This commit limits the scope with which most jobs are running and only allows broader scope where necessary

ci: Limit Github Actions token scope

---

.github/workflows/cicd.yaml
.github/workflows/nightly-scans.yaml
.github/workflows/release.yaml
tests/integration/integration-test.sh

The older k8 versions (v1.16 - v1.19) are failing the pipeline. Since they reached their end of life anyways, they have been removed temporarily until we find a fix.

ci: temporarily removed old k8s versions

---

.github/actions/k3s-cluster/action.yaml
.github/workflows/cicd.yaml
.github/workflows/nightly-scans.yaml

- Changes the deprecated set-output command in the CI
- Fixes tests for older k8s versions

ci: Change deprecated set-output to GITHUB_OUTPUT variable and re-enable legacy k8s tests

---

connaisseur/image.py
tests/test_image.py

Just because you've augmented an image with a new property ("digest") doesn't mean you get to clear a different value ("tag") in the setter.
Fixes: N/A (or, more correctly: future pain when tag preservation in patch is implemented)
Image tags are valid properties of the image.  You shouldn't arbitrarily throw the tag away once you've set a digest.
I intend for you to preserve this image tag in the patch based on a config setting in a subsequent PR, but first I need to test your willingness to adapt here with this change.
I can't keep using your solution if we can't take these steps together to preserve my image tags.

Don't clear image tag

---

.github/actions/safety/action.yaml
.github/workflows/cicd.yaml
docker/Dockerfile

There was a problem with the frozenlist package, which didn't had its packages added to wheels (https://github.com/aio-libs/frozenlist/issues/342). The packages are now added, so the fix for this can be reverted, except for the pytest job which is the only one building on a debian image (faster runtime). Here the yarl and multidict packages still have the same problem as frozenlist had. Waiting fo a fix here.

fix: revert frozenlist changes

---

connaisseur/admission_request.py
connaisseur/flask_application.py
connaisseur/workload_object.py
docs/features/automatic_update_approval.md
helm/Chart.yaml
helm/templates/env.yaml
helm/values.yaml
tests/conftest.py
tests/data/sample_admission_requests/ad_request_auto_update_approval.json
tests/test_flask_application.py
tests/validators/notaryv1/test_trust_data.py

Added a feature flag that enables auto update approval. When active, Connaisseur automatically allows updates to resources in which no changes to image references were made.
fixes  #820

feat: auto update approval

---

.github/actions/trivy/action.yaml
.trivyignore
connaisseur/alert.py
connaisseur/exceptions.py
connaisseur/flask_application.py
connaisseur/image.py
connaisseur/util.py
connaisseur/validators/cosign/cosign_validator.py
connaisseur/validators/notaryv1/notary.py
connaisseur/validators/notaryv1/notaryv1_validator.py
connaisseur/validators/static/static_validator.py
scripts/changelogger.py
tests/conftest.py
tests/test_alert.py
tests/test_config.py
tests/test_flask_application.py
tests/test_util.py
tests/test_workload_object.py
tests/validators/cosign/test_cosign_validator.py
tests/validators/notaryv1/test_keystore.py
tests/validators/notaryv1/test_notary.py
tests/validators/notaryv1/test_notaryv1_validator.py
tests/validators/notaryv1/test_trust_data.py
tests/validators/static/test_static_validator.py

Fixes no issue
- ignore trivy config rules for secrets
- switch all trivy scans to aquasecurity gh action
- fix black

fix: ignore secret scanning config rules for trivy config scanner

---

.dockerignore
connaisseur/alert.py
connaisseur/config.py
connaisseur/constants.py
connaisseur/flask_application.py
connaisseur/validators/cosign/cosign_validator.py
connaisseur/validators/notaryv1/notary.py
connaisseur/validators/notaryv1/notaryv1_validator.py
docs/CONTRIBUTING.md
tests/test_flask_application.py
tests/validators/notaryv1/test_notary.py
tests/validators/notaryv1/test_notaryv1_validator.py

Admission control is capped to 30s. As such Connaisseur must finish within these 30s or it will fail generically. To add information to this failure, this MR adds a 29s timeout to all validation activities and fails with a dedicated error message if the timeout is surpassed
The MR also contains minor fixes to docs and build I noticed when touching it
Fixes #448

Fix mutate timeout

---

scripts/get_root_key.py

The root key script was broken with https://github.com/sse-secure-systems/connaisseur/pull/873 due to a new argument added to an internal function, which the root key script uses. This commit adds that missing argument to the call inside the root key script

Fix: Repair script for getting root key

---

connaisseur/flask_application.py
connaisseur/validators/cosign/cosign_validator.py
tests/data/cosign/notfound_in_tl.txt

Fixes no issue
- cosign output for failing verification of an image w/o rekor entry was changed
- connaisseur was adapted to change

fix: cosign output adjusted to new error

---

.github/actions/context/action.yaml
docs/RELEASING.md

This commit ammends the release documentation to allow publishing both the master branch and the release tag at the same time.

Fix release docs

---

connaisseur/config.py
helm/Chart.yaml
helm/templates/_helpers.tpl
helm/templates/alertconfig.yaml
helm/templates/config-secrets.yaml
helm/templates/deployment.yaml
helm/values.yaml
tests/integration/integration-test.sh

Only deploy alerting ConfigMap and Secret if defined
Previously, we deployed some resources even if they weren't used in the deployment. This reduces the number of instances where that happens

Only deploy ConfigMaps and Secrets if needed

---

.github/PULL_REQUEST_TEMPLATE.md
.github/actions/build/action.yml
.github/actions/context/action.yaml
.github/workflows/.reusable-integration-test.yml
.github/workflows/cicd.yaml
.github/workflows/nightly-build.yaml
.github/workflows/release.yaml
Makefile
docs/RELEASING.md
helm/Chart.yaml
helm/templates/deployment.yaml
helm/values.yaml
tests/integration/ghcr-values.yaml
tests/integration/var-img.yaml

To get less hassle and generally improve the config, we default to the current Helm appVersion instead of having an additional configuration toggle in the values.yaml. While the toggle exists, it is discouraged and not enabled by default.

build: Default to appVersion

---

tests/integration/integration-test.sh

During the release workflow, connaisseur tried to validate itself with cosign, for which no signature existed. Fixing this.
Fixes #

ci: fix release workflow

---

Makefile
connaisseur/trust_root.py
connaisseur/validators/cosign/cosign_validator.py
docs/validators/sigstore_cosign.md
tests/integration/cases.yaml
tests/integration/update.yaml
tests/test_trust_root.py

Fixes #201
- support of rsa public keys for cosign validator is added

feat: support cosign rsa keys

---

connaisseur/validators/cosign/cosign_validator.py

With the functionality for cosign validators to validate multiple signatures with different keys and meeting certain thresholds, the logging output for these can be confusing. It is expected that certain keys do not match a signature and that an error is logged, even though the overall verification is successfull. To reduce confusion here and to make it clear the verification was actually sucessfull, the error logging was set to debug instead of info.
fixes #977

fix: less verbose logging for cosign

---

connaisseur/flask_application.py
docs/features/metrics.md

When monitoring Connaissuer via the prometheus metrics endpoint, there was previously no way to detect failures when detection mode was turned on, as it changed the status code and 'allowed' field to True (as designed). This change adds a boolean label to the metric that indicates whether warnings are present - and warnings are only present when the operation would have failed but detection mode is on.

Make failures visible via metrics in detection mode

---

.github/dependabot.yml

Groups all dependabot PRs into single one's per package type. [Docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups).

ci: grouping of dependabot PRs

---

helm/Chart.yaml
helm/templates/deployment.yaml
helm/values.yaml

The current helm chart does not permit to add a pod-level security context, only a container-level security context. The helm chart is extended with an optional pod-level security context.
Fix #1240
duplicate of #1242

feat: Add pod securityContext to helm chart

---

.github/workflows/.reusable-sast.yml
.github/workflows/.reusable-unit-test.yml
docker/Dockerfile

Some packages currently do not work with python 3.12, so we explicitly use python 3.11.

fix: switch to python 3.11

---

.pylintrc
connaisseur/flask_application.py
connaisseur/workload_object.py
tests/conftest.py
tests/data/sample_admission_requests/ad_request_replica_from_non_zero.json
tests/data/sample_admission_requests/ad_request_replicaset_from_zero.json
tests/data/sample_admission_requests/ad_request_replicaset_to_zero.json
tests/test_flask_application.py

When updating a deployment form image A to B a new replicaset is created for image B and the old replicaset is set to 0 replicas. Previously Connaisseur tried to validated the previous replicasets update request, which may fail because image A no longer has a valid signature. This validation is now skipped.
fixes #1224

fix: skip replica to zero

---

tests/integration/cases.yaml
tests/integration/integration-test.sh

With #1282 new test images were pushed, thus changing the signed digests. The previous digest was pinned inside the regular integration test. This has been updated.

fix: fix regular integration test

---

helm/Chart.yaml
helm/templates/deployment.yaml

Specifying the containerPort, on the one hand, has a documentary purpose, by making explicit which ports are exposed by the container. On the other hand, it permits the usage of other tools that rely on the containerPort, like PodMonitors from the prometheus operator.
Fix #1305
duplicated from #1306 because of pipeline issue with external PRs

feat: explicitly specify containerPort in helm chart

---

connaisseur/workload_object.py
docs/CONTRIBUTING.md
docs/SECURITY.md
helm/templates/certificate_webhook-conf.yaml
tests/conftest.py
tests/data/sample_admission_requests/ad_request_ephemeral_container.json
tests/data/sample_admission_requests/ad_request_ephemeral_container_unchanged.json
tests/integration/cases.yaml
tests/integration/integration-test.sh
tests/test_flask_application.py
tests/test_workload_object.py

When ephemeral containers got introduced, we missed including them in admission reviews. This would've allowed an attacker to circumvent Connaisseur's signature verification if they could spawn ephemeral containers in the cluster. This PR remedies the issue.

Feat: Validate ephemeral containers

---

tests/integration/integration-test.sh

Add message to retry of deployment during integration test, such that if a deployment fails multiple times, we can identify this in the logs

test: Add message to retry of deployment during integration test

---

.github/workflows/.reusable-integration-test.yml
tests/integration/integration-test.sh
tests/integration/update.yaml

Multiple improvements to the integration test setup
This PR includes some improvements with respect to the integration test setup
- Most tests are run on a single Connaisseur replica for easier debugging should things go wrong
- If part of the main integration test fails, integration tests that include uninstallation of Connaisseur will not uninstall it such that the k8s logs are preserved
- In case a failure occurs, the whole set of logs (instead of the last 10 entries) are printed, giving way better debugging data

Multiple improvements to the integration test setup

---

connaisseur/__main__.py
connaisseur/flask_application.py
tests/integration/integration-test.sh

We fail sometimes like [here](https://github.com/sse-secure-systems/connaisseur/actions/runs/6655707388/job/18086653425) with `RuntimeError: Timeout context manager should be used inside a task`, which this PR fixes.
Using the default initialization of the event loop (i.e. not doing it ourselves) seems to fix the problem (locally ran into RuntimeErrors 5/20 complexity integration tests before and 0/20 after fix)

Fix RuntimeError

---

.github/workflows/.reusable-compliance.yml
.github/workflows/release.yaml
connaisseur/constants.py
connaisseur/flask_application.py
connaisseur/res/targets_schema.json
docs/CONTRIBUTING.md
docs/SECURITY.md
scripts/changelogger.py
scripts/security_annotation.sh
tests/data/trust_data/redos_targets.json
tests/test_flask_application.py
tests/validators/notaryv1/test_trust_data.py

Fixes a RE DoS in Connaisseur
This MR contains multiple commits. One fixes a RE DoS in Connaisseur's validation of TUF data. Another improves the conceptually (but technically unrelated) handling of timeouts of asynchronous function calls. The remaining commits handle a new type of commit header, which will allow us to automatically publish the Helm charts with a sec release annotation.

Fix DoS vulnerability

---

tests/integration/integration-test.sh

test: get logs on error case of other-ns integration test

---

docs/basics.md
helm/Chart.yaml
helm/values.yaml
tests/data/config/err2.yaml
tests/data/config/err3.yaml
tests/data/config/err4.yaml
tests/data/config/sample_config.yaml
tests/integration/update-for-workloads.yaml
tests/integration/update-self-hosted-notary.yaml
tests/integration/update.yaml
tests/test_config.py
tests/test_flask_application.py
tests/test_image.py

Context: https://kubernetes.io/blog/2023/03/10/image-registry-redirect/

update: Update k8s image registry in default policy

---

connaisseur/exceptions.py
connaisseur/validators/notaryv1/notary.py
helm/Chart.yaml
tests/conftest.py
tests/validators/notaryv1/test_notary.py

Previously, auth failures when retrieving TUF trust data were raised as exceptions, but never handled, thus leading to opaque 'unknown error' messages. This commit introduces handling for 401s, thus making the admission review clearer.

fix: Report notary auth failure

---

.github/actions/safety/action.yaml
.github/workflows/.reusable-sca.yml
docker/Dockerfile
requirements.txt

Due to confusion of a developer, the safety package was part of the Connaisseur container. This is no longer the case, the package is now installed during the CI, where it is exclusivly needed.

build: removed safety

---

connaisseur/__main__.py
connaisseur/validators/cosign/cosign_validator.py
scripts/get_root_key.py
tests/integration/cases.yaml
tests/integration/integration-test.sh
tests/testimages/double_sig/Dockerfile
tests/testimages/double_sig/main.c
tests/testimages/signed/Dockerfile
tests/testimages/signed/main.c
tests/testimages/special_sig/Dockerfile
tests/testimages/special_sig/main.c
tests/testimages/unsigned/Dockerfile
tests/testimages/unsigned/main.c
tests/testimages/wrong_signer/Dockerfile
tests/testimages/wrong_signer/main.c

Because of expired signature data, new signatures needed to be created. At the same time we decided to minimize the size of our testimages.

ci: new testimages

---

tests/integration/run_integration_tests.sh

Executing the run_integration_tests script hasn't worked for minikube users so far. This issue has now been fixed with a simple oneliner.

fix: Added oneliner to fix issues with minikube

---

.github/actions/build/action.yml
.github/workflows/.reusable-cleanup-registry.yml

CI: Disable non-OCI-compliant provenance and disable image cleanup during public Golang test

---

.github/workflows/.reusable-publish.yml
.github/workflows/publish.yml
.github/workflows/release.yaml

Allows a manual publish action to run the last stage of the release pipeline manually, circumventing prior checks.

ci: add manual publish job

---

.github/workflows/nightly.yaml

ci: fix wrong job dependency

---

.github/workflows/.reusable-ci.yml
.github/workflows/nightly-build.yaml
.github/workflows/nightly.yaml
.github/workflows/pr.yml
.github/workflows/push.yml

Fixes the CI after a new permission was added that is now missing from our default-deny list
Context: https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/

ci: Adapt workflow files to new attestation permission

---

charts/connaisseur/Chart.yaml
charts/connaisseur/templates/deployment.yaml
charts/connaisseur/templates/env.yaml
charts/connaisseur/templates/redis.yaml
charts/connaisseur/values.yaml
cmd/connaisseur/main.go
docs/features/automatic_unchanged_approval.md
docs/features/caching.md
internal/caching/caching.go
internal/caching/caching_test.go
internal/caching/empty.go
internal/caching/empty_test.go
internal/caching/redis.go
internal/caching/redis_test.go
internal/constants/constants.go
internal/handler/mutate_test.go
internal/handler/validation/skip.go
internal/handler/validation/skip_test.go
internal/handler/validation/validation.go
test/testhelper/mock_cache.go

Fixes #1587 in its basic form, though it doesn't allow configuring a remote Redis
This PR makes the cache expiry time of entries in the Redis configurable. If cache expiry is set to 0, the Redis deployment is cut from Connaisseur's deployment.

feat: Configurable cache expiry

---

charts/connaisseur/templates/env.yaml
charts/connaisseur/values.yaml
docs/features/caching.md
internal/caching/caching.go
internal/caching/caching_test.go
internal/constants/constants.go
internal/handler/validation/validation.go
internal/handler/validation/validation_test.go

This PR adds configuration options to decide whether to cache errors

feat: Allow to configure whether to cache errors

---

charts/connaisseur/templates/env.yaml
charts/connaisseur/templates/role.yaml
charts/connaisseur/templates/rolebinding.yaml

Before this commit, there were different cases where Connaisseur mishandled default values in its config, if their parent keys were not set in the values.yaml. Resulting errors could've been anything between inconsequential (additional log entry) and fatal (e.g. missing deployment of Role). This commit fixes handling of these values.

fix: Fix handling of undefined values in values.yaml

---

docs/validators/notaryv1.md

With the switch to Golang the authentication secrets require to be named `secret.yaml` instead of the previous `auth.yaml`. This has been fixed in the documentation.

docs: fix secret file reference

---

internal/validator/notaryv1/notaryv1_validator.go
internal/validator/notaryv1/notaryv1_validator_test.go
test/testdata/notaryv1/15_DER_key_format.yaml

When using a nv1 validator and provide DER formated keys, Connaisseur panics as it tries to load a nil key. This has been fix with a fitting error message.
fixes #1594

fix: error handling for DER formated keys

---

charts/connaisseur/README.md

Brings back the README.md file in the helm chart, that was used as a description for the Connaisseur package on ArtifactHub.

docs: revert artifact hub docs

---

charts/connaisseur/Chart.yaml
internal/handler/validation/validation.go

Remove unused reqId parameter from logging

fix: Remove unset reqId parameter from logging

---

build/Dockerfile

The version for the ca-certificates package, installed during an intermediate build step from an alpine image, is being unpinned. Reason for that is that alpine only ever provides a single version for their packages and once they update the ca-certificates packages, the Connaisseur build automatically fails, since the previous used version is no longer available.

build: unpin ca certificates

---

internal/handler/mutate.go
internal/handler/mutate_test.go

When Connaisseur was done with the verification and returned an empty patch, the patch type was still set to JSONPatch. Kubernetes handled this regardless, but other tools like ArgoCD did not and threw an error. Connaisseur will now neither set a patch nor patch type and leave those fields empty, so it's compatible with other tools.
Fixes #1705

fix: return empty patch type if there is no patch

---

test/integration/redis-cert/test.sh

The redis cert test tested that after upgrading a redis with a custom certificate the caching mechanism still worked. Problem was, the redis instance might have been ready on Kubernetes side, but internally not ready to receive connections. Thus the caching was tested and failed, before the newly upgraded redis was ready. This has been fixed with a wating mechanism.

test: fix flakey redis-cert test

---

charts/connaisseur/Chart.yaml
charts/connaisseur/templates/deployment.yaml

Duplicate of #1735 because of pipeline permission issues ... 😞 
From chart version 2.4, a refactor was made that places connaisseur-env-secret under 'env' instead of under 'envFrom' in the deployment.This breaks cosign validations that require custom secrets like ECR
Fixes #1734

fix: correctly place connaisseur-env-secret in deployment yaml

---

docs/validators/sigstore_cosign.md
scripts/upgrade_to_version_3.py

The `--k8-keychain` feature provided by cosign is supported by Connaisseur with the `auth.k8sKeychain` option in validator configurations. This option was internally renamed to `auth.useKeychain` without mentioning this change inside the documentation. This has been fixed.
fixes #1766

docs: fixed k8-keychain renaming

---

charts/connaisseur/Chart.yaml
charts/connaisseur/templates/deployment.yaml
charts/connaisseur/values.yaml

Added the option to define costume annotation to the Connaisseur deployment.
fixes #1765
credits to @edison-vflow

feat: added customizable annotations

---

charts/connaisseur/templates/redis.yaml
charts/connaisseur/values.yaml

Fixes #1794 
This commit adds the ability to override redis image repository and tag from the values.yaml file. Currently, this is hardcoded.

feat: ability to override redis image in values.yaml

---

.github/workflows/.reusable-publish.yml

Before, both publish jobs tried to change the gh-pages branch simultaneously, often leading to failed jobs which needed to be retried manually. This commit adds a dependency such that the jobs run after one another.

ci: Deparallelize publish jobs

---

.github/actions/trivy-config/action.yaml
.github/actions/trivy-image/action.yaml
.github/workflows/.reusable-sca.yml

Recently, trivy scans failed due to ratelimiting on the pull of its vulnerability DBs. See https://github.com/aquasecurity/trivy-action/issues/389. This PR adds a fallback download URI pointing to the official AWS artifacts.

ci: Set fallback AWS repository for ratelimited trivy DBs

---

.github/dependabot.yml

By default, dependabot doesn't run on local actions. This PR adds each subfolder of .github/actions as a folder for dependabot to search outdated actions.

ci: Enable dependabot for local actions

---

charts/connaisseur/Chart.yaml
charts/connaisseur/values.yaml

Previously, we set the default security context of the Redis to a user/group not taken. This could cause problems with permissions, resulting in error logs and shutdown delays, thus this commit changes the default user/group to reflect the built-in redis user.
Fixes #1764

fix: Change security context of Redis image to match redis user

---

internal/handler/validation/validation.go
internal/handler/validation/validation_test.go

The check on the validation mode is done by lower casing the input and comparing it to a constant. Unfortunately the constant wasn\'t entirely lower case. This has been fixed.
fixes #1816

fix: validation mode lower case

---

charts/connaisseur/Chart.yaml
charts/connaisseur/templates/env.yaml
charts/connaisseur/values.yaml
cmd/connaisseur/main.go
internal/constants/constants.go
internal/utils/logging.go
internal/utils/logging_test.go

Also introduces a structure to add more log formats should the need arise. Does not change the default of logging prettified json.
> Duplicates #1842, since pipeline can only be run by repo members (sadly).

feat: support single-line json as log format

---

.github/workflows/107_integration-test.yml

The docker package is already installed in the ubunutu version of github runners and thus doesn't need to be installed. Also the package no longer is available in the default apt repositories anyways.

ci: remove docker package installation

---

.github/workflows/104_sast.yml
charts/connaisseur/Chart.yaml
charts/connaisseur/values.yaml
test/integration/common_functions.sh
test/integration/complexity/complex_deployment.yaml
test/integration/complexity/install.yaml
test/integration/complexity/test.sh
test/integration/deployment/deployments/deployment_i1.yaml
test/integration/deployment/deployments/deployment_i2.yaml
test/integration/deployment/deployments/deployment_i2i.yaml
test/integration/deployment/deployments/deployment_i2ui.yaml
test/integration/deployment/install.yaml
test/integration/load/install.yaml
test/integration/load/load.yaml
test/integration/load/test.sh
test/integration/notaryv1/cases.yaml
test/integration/notaryv1/install.yaml
test/integration/pre-config/cases.yaml
test/integration/self-hosted-notary/install.yaml
test/integration/workload/install.yaml

The official Docker Content Trust certs started to expire, see https://www.docker.com/blog/retiring-docker-content-trust/. Since they will not be updated, all tests including previously signed official images fail. This commit adapts our tests to use our own test images instead

test: Replace official Docker images with custom images
